// ~~ Generated by projen in mxr/base. Modifications will be overwritten on the next sync. To modify properly, edit .github/base.yml and retrigger the propagate workflow in mxr/base.

const config = {
  plugins: ["@tailwindcss/postcss"],
};

export default config;
