name: tests

on:
  pull_request:
    paths: &project_files
    - .github/workflows/**
    - app/**
    - lib/**
    - tests/**
    - scripts/**
    - '**/*.css'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.mjs'
    - '**/*.mts'
    - '**/*.ts'
    - '**/*.tsx'
    - '**/*.json'
    - package.json
    - package-lock.json
  push:
    branches: [main]
    paths: *project_files

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      project_files: ${{ steps.filter.outputs.project_files }}
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          project_files:
            - .github/workflows/**
            - app/**
            - lib/**
            - tests/**
            - scripts/**
            - '**/*.css'
            - '**/*.js'
            - '**/*.jsx'
            - '**/*.mjs'
            - '**/*.mts'
            - '**/*.ts'
            - '**/*.tsx'
            - '**/*.json'
            - package.json
            - package-lock.json

  test-real:
    needs: [changes]
    if: needs.changes.outputs.project_files == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Setup Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: package.json
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run lint (auto-fix)
      run: npm run lint

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: coverage-report
        path: coverage

  test:
    needs: [changes, test-real]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - run: |
        if [ "${{ needs.changes.outputs.project_files }}" != "true" ]; then
          exit 0
        fi
        if [ "${{ needs.test-real.result }}" != "success" ]; then
          exit 1
        fi
